import os from 'node:os';

process.env.APP_ENV ??= 'test';
process.env.FRONTEND_URL ??= 'http://localhost:5173';
process.env.API_BASE_URL ??= 'http://localhost:8787';

const defaultLocalPostgresUser = process.env.PGUSER?.trim() || os.userInfo().username;
const defaultTestDatabaseUrl = `postgresql://${encodeURIComponent(defaultLocalPostgresUser)}@localhost:5432/iishka_service_test?schema=public`;
const testDatabaseUrl = process.env.TEST_DATABASE_URL?.trim() || defaultTestDatabaseUrl;
const testDirectUrl = process.env.TEST_DIRECT_URL?.trim() || testDatabaseUrl;
const testMigrationUrl = process.env.TEST_MIGRATION_DATABASE_URL?.trim() || testDirectUrl;

process.env.DATABASE_URL = testDatabaseUrl;
process.env.DIRECT_URL = testDirectUrl;
process.env.MIGRATION_DATABASE_URL = testMigrationUrl;
process.env.JWT_SECRET ??= 'test-secret-test-secret-test-secret';
process.env.SESSION_TTL_MINUTES ??= '60';
process.env.TELEGRAM_INIT_DATA_TTL_SECONDS ??= '3600';
process.env.TELEGRAM_BOT_TOKEN ??= '123456:telegram-test-token';
process.env.TELEGRAM_BOT_USERNAME ??= 'iishka_test_bot';
process.env.TELEGRAM_WEBHOOK_SECRET ??= 'telegram-webhook-secret';
process.env.TELEGRAM_MINI_APP_URL ??= 'https://mini-app.example.com';
process.env.TELEGRAM_DELIVERY_MODE ??= 'disabled';
process.env.OPENAI_API_KEY ??= 'test-openai-key';
process.env.OPENAI_MODEL ??= 'gpt-5.4-mini';
process.env.ANTHROPIC_API_KEY ??= 'test-anthropic-key';
process.env.ANTHROPIC_MODEL ??= 'claude-3-5-sonnet-latest';
process.env.GOOGLE_AI_API_KEY ??= 'test-google-key';
process.env.GOOGLE_AI_MODEL ??= 'gemini-2.0-flash';
process.env.NANO_BANANA_MODEL ??= 'gemini-2.5-flash-image';
process.env.MAX_UPLOAD_BYTES ??= '10485760';
process.env.ALLOWED_UPLOAD_MIME_TYPES ??= 'application/pdf,image/png,image/jpeg,text/plain';
process.env.UPLOAD_STORAGE_DRIVER ??= 'local';
process.env.UPLOAD_LOCAL_DIR ??= './storage/uploads';
process.env.RATE_LIMIT_WINDOW_SECONDS ??= '60';
process.env.RATE_LIMIT_MAX_REQUESTS ??= '120';
process.env.ENABLE_DEV_AUTH ??= 'true';
process.env.DEV_AUTH_SHARED_SECRET ??= 'dev-secret';
process.env.ENABLE_DEV_SUBSCRIPTION_OVERRIDE ??= 'true';
process.env.PORT ??= '8787';
